<?php

return [
    'pages' => [
        'founder' => [
            'path' => '/founder',
            'title' => 'Dr. Elizabeth Consoli — Founder of ORIGINA™',
            'description' => 'Dr. Elizabeth Consoli, MD, MBChB — Medical Doctor, Cosmetic Formulation Scientist, and Founder of ORIGINA™.',
            'hero' => [
                'crumb' => 'Founder',
                'kicker' => 'Institutional leadership',
                'title' => 'Dr. Elizabeth',
                'accent' => 'Consoli.',
                'intro' => 'MD, MBChB · Medical Doctor · Cosmetic Formulation Scientist · Founder of ORIGINA™',
                'image' => '/img/founder/founder-01.jpeg',
                'alt' => 'Dr. Elizabeth Consoli in her clinical environment',
                'caption' => 'Scientific direction · Dar es Salaam',
            ],
            'nav' => [
                ['id' => 'roles', 'label' => 'Roles'],
                ['id' => 'origin', 'label' => 'Origin'],
                ['id' => 'mandate', 'label' => 'Mandate'],
            ],
            'sections' => [
                [
                    'id' => 'roles',
                    'type' => 'split',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Roles',
                    'title' => 'Institutional roles',
                    'lead' => 'The founder establishes scientific direction, but ORIGINA is designed to become larger than any individual.',
                    'items' => [
                        'Founder & Director — ORIGINA™',
                        'Founder / Scientific Director — ORIGINA Labs™',
                        'Creator — BMX-24™ platform',
                        'Focus — Skin of colour, formulation science and biological systems',
                    ],
                    'image' => '/img/founder/founder-01.jpeg',
                    'image_alt' => 'Dr. Elizabeth Consoli in a clinical environment',
                    'caption' => 'Medicine · Formulation · Institution building',
                ],
                [
                    'id' => 'origin',
                    'type' => 'prose',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Origin',
                    'title' => 'Scientific platforms from Africa.',
                    'lead' => 'Dr. Elizabeth Consoli founded ORIGINA around a conviction that scientific innovation does not need to originate elsewhere to be globally relevant.',
                    'paragraphs' => [
                        'Her early work sits at the intersection of medicine, dermatology, formulation science, and the needs of skin of colour.',
                        'That initial focus expands into a broader institutional vision: build scientific platforms from Africa capable of serving global populations.',
                    ],
                    'quote' => 'Build scientific platforms from Africa capable of serving global populations.',
                ],
                [
                    'id' => 'mandate',
                    'type' => 'split',
                    'tone' => 'paper',
                    'eyebrow' => '03 · Mandate',
                    'title' => 'Reinforce the institution, not celebrity.',
                    'lead' => 'The founder establishes the intellectual culture; the institution is designed to carry it forward.',
                    'paragraphs' => [
                        'ORIGINA is deliberately structured so scientific standards, institutional memory, quality systems, and multidisciplinary capability can outlive individual leadership.',
                    ],
                    'image' => '/img/founder/founder-09.jpeg',
                    'image_alt' => 'Dr. Elizabeth Consoli in professional conversation',
                    'caption' => 'Leadership through institution building',
                    'reverse' => true,
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Explore the institution she is building.',
                'links' => [
                    ['href' => '/about', 'label' => 'The institution'],
                    ['href' => '/labs', 'label' => 'ORIGINA Labs™', 'secondary' => true],
                ],
            ],
        ],

        'africa' => [
            'path' => '/africa',
            'title' => 'Africa Originating — ORIGINA™',
            'description' => 'Africa is the origin, not the limitation. ORIGINA is headquartered in Dar es Salaam, Tanzania, and designed for global relevance.',
            'hero' => [
                'crumb' => 'Africa Originating',
                'kicker' => 'Institutional origin',
                'title' => 'Africa is the origin.',
                'accent' => 'Not the limitation.',
                'intro' => 'Headquartered in Dar es Salaam, Tanzania. Geography is not presented as a ceiling.',
                'image' => '/img/founder/founder-08.jpeg',
                'alt' => 'Dr. Elizabeth Consoli with a multidisciplinary professional community',
                'caption' => 'Dar es Salaam · Tanzania',
            ],
            'nav' => [
                ['id' => 'conviction', 'label' => 'Conviction'],
                ['id' => 'headquarters', 'label' => 'Headquarters'],
                ['id' => 'world', 'label' => 'Global relevance'],
            ],
            'sections' => [
                [
                    'id' => 'conviction',
                    'type' => 'split',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Conviction',
                    'title' => 'Global relevance from African origin.',
                    'lead' => 'ORIGINA is built on the conviction that Africa can originate scientific platforms, clinical research, advanced formulations, intellectual property, technology, global brands, and institutions.',
                    'quote' => 'The ambition is not to build an African version of an existing foreign company. The ambition is to build something globally relevant that happens to have originated in Africa.',
                    'paragraphs' => [
                        'Africa is represented through institutional confidence—not stereotypes. Scientific rigor, intellectual ambition, and long-term institutional permanence carry the story.',
                    ],
                    'image' => '/img/founder/founder-04.jpeg',
                    'image_alt' => 'Dr. Elizabeth Consoli sharing a community event moment',
                    'caption' => 'Origin · Community · Exchange',
                    'reverse' => true,
                ],
                [
                    'id' => 'headquarters',
                    'type' => 'prose',
                    'tone' => 'noir',
                    'eyebrow' => '02 · Headquarters',
                    'title' => 'A global institution with African origin.',
                    'lead' => 'A multi-divisional innovation institution designed for worldwide relevance.',
                    'paragraphs' => [
                        'Dar es Salaam is the institutional base. The ambition is to build research, product-development, education, manufacturing, and intellectual-property capability that can participate globally without hiding where it began.',
                    ],
                ],
                [
                    'id' => 'world',
                    'type' => 'statement',
                    'tone' => 'sunk',
                    'eyebrow' => 'Institutional statement',
                    'title' => 'Beginning in Africa. Serving the world.',
                    'quote' => 'Africa is an origin point for scientific ambition, not a boundary around it.',
                    'meta' => 'Dar es Salaam · Tanzania · Biology First™',
                ],
            ],
            'cta' => [
                'eyebrow' => 'Collaboration',
                'title' => 'Build with ORIGINA.',
                'links' => [
                    ['href' => '/contact', 'label' => 'Start a conversation'],
                ],
            ],
        ],

        'biology-first' => [
            'path' => '/biology-first',
            'title' => 'Biology First™ — ORIGINA',
            'description' => 'Biology First™ is ORIGINA’s philosophical framework: every innovation begins by understanding living systems.',
            'hero' => [
                'crumb' => 'Biology First™',
                'kicker' => 'ORIGINA / Science',
                'title' => 'Biology First™',
                'accent' => 'Understand before intervention.',
                'intro' => 'Every innovation begins by understanding living systems.',
                'image' => '/img/founder/founder-05.jpeg',
                'alt' => 'Dr. Elizabeth Consoli explaining formulation science',
                'caption' => 'Scientific thinking in practice',
            ],
            'nav' => [
                ['id' => 'systems', 'label' => 'Systems thinking'],
                ['id' => 'principles', 'label' => 'Principles'],
                ['id' => 'evidence', 'label' => 'Evidence'],
            ],
            'sections' => [
                [
                    'id' => 'systems',
                    'type' => 'numbered',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Systems thinking',
                    'title' => 'Interconnected biology.',
                    'intro' => 'Pigmentation, inflammation, barrier function, environment, cellular ageing, and metabolic stress do not operate in isolation.',
                    'items' => [
                        ['title' => 'Pigmentation', 'text' => 'Melanin biology is studied in relation to inflammatory, environmental, and structural context.'],
                        ['title' => 'Inflammation', 'text' => 'Inflammatory pathways can influence visible outcomes and tolerability.'],
                        ['title' => 'Barrier function', 'text' => 'The skin barrier is part of the system, not an afterthought.'],
                        ['title' => 'Environment', 'text' => 'Exposure, climate, behaviour, and geography can modify biological context.'],
                        ['title' => 'Cellular ageing', 'text' => 'Ageing-related biological processes interact with tissue function over time.'],
                        ['title' => 'Metabolic stress', 'text' => 'Cellular stress and resilience shape the conditions within which interventions operate.'],
                    ],
                ],
                [
                    'id' => 'principles',
                    'type' => 'cards',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Four principles',
                    'title' => 'A framework for innovation.',
                    'intro' => 'Every programme begins by understanding living systems before designing intervention.',
                    'items' => [
                        ['meta' => 'Principle 01', 'title' => 'Biology First™', 'text' => 'Every innovation begins by understanding living systems.'],
                        ['meta' => 'Principle 02', 'title' => 'Systems Thinking™', 'text' => 'Pigmentation, inflammation, barrier function, ageing, cellular processes and environmental exposure interact.'],
                        ['meta' => 'Principle 03', 'title' => 'Platform Innovation™', 'text' => 'Develop scientific platforms capable of supporting multiple products, protocols and applications.'],
                        ['meta' => 'Principle 04', 'title' => 'Evidence Before Exaggeration', 'text' => 'The strength of a claim must correspond to the strength of the evidence.'],
                    ],
                ],
                [
                    'id' => 'evidence',
                    'type' => 'statement-list',
                    'tone' => 'noir',
                    'eyebrow' => '03 · Evidence before exaggeration',
                    'title' => 'Evidence has a progression.',
                    'intro' => 'Evidence levels are not interchangeable with marketing claims.',
                    'items' => [
                        'A scientific hypothesis is not a clinical result.',
                        'A promising formulation is not automatically a proven treatment.',
                        'A laboratory mechanism is not automatically evidence of human clinical efficacy.',
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the scientific position.',
                'links' => [
                    ['href' => '/science#position', 'label' => 'Scientific position'],
                    ['href' => '/science/responsible-science', 'label' => 'Responsible science', 'secondary' => true],
                ],
            ],
        ],

        'culture' => [
            'path' => '/culture',
            'title' => 'Culture & Talent — ORIGINA',
            'description' => 'Discover the standards, values, expectations, and people philosophy behind ORIGINA.',
            'hero' => [
                'crumb' => 'Culture',
                'kicker' => 'Culture & talent',
                'title' => 'We do not seek employees.',
                'accent' => 'We seek builders.',
                'intro' => 'Every member is expected to contribute ideas, not simply perform tasks. Credentials are respected. Capability is required. Character is essential.',
                'image' => '/img/founder/founder-08.jpeg',
                'alt' => 'Dr. Elizabeth Consoli with a multidisciplinary professional community',
                'caption' => 'Multidisciplinary culture',
            ],
            'nav' => [
                ['id' => 'people', 'label' => 'People'],
                ['id' => 'standard', 'label' => 'Standard'],
                ['id' => 'work', 'label' => 'How we work'],
            ],
            'sections' => [
                [
                    'id' => 'people',
                    'type' => 'tags',
                    'tone' => 'paper',
                    'eyebrow' => '01 · People',
                    'title' => 'The person behind the work.',
                    'lead' => 'ORIGINA is built by people whose thinking, discipline, and character compound over time.',
                    'items' => ['Curiosity', 'Integrity', 'Problem solving', 'Discipline', 'Initiative', 'Critical thinking', 'Excellence'],
                ],
                [
                    'id' => 'standard',
                    'type' => 'cards',
                    'tone' => 'noir',
                    'eyebrow' => 'The ORIGINA Standard',
                    'title' => 'Eight values. One way of operating.',
                    'intro' => 'Not slogans on a wall. Expectations visible in decisions, quality, responsibility, and how people treat one another.',
                    'items' => [
                        ['meta' => '01', 'title' => 'Excellence', 'text' => 'A standard embedded in every formula, decision, and interaction.'],
                        ['meta' => '02', 'title' => 'Accountability', 'text' => 'Ownership of outcomes, not only effort.'],
                        ['meta' => '03', 'title' => 'Innovation', 'text' => 'The willingness to question, rebuild, and imagine.'],
                        ['meta' => '04', 'title' => 'Integrity', 'text' => 'Intellectual honesty and transparency without exception.'],
                        ['meta' => '05', 'title' => 'Curiosity', 'text' => 'The belief that every answer opens new questions.'],
                        ['meta' => '06', 'title' => 'Long-term thinking', 'text' => 'Building for the next generation, not the next quarter.'],
                        ['meta' => '07', 'title' => 'Discipline', 'text' => 'The bridge between intention and achievement.'],
                        ['meta' => '08', 'title' => 'Respect', 'text' => 'For people, science, ideas, and the communities we serve.'],
                    ],
                ],
                [
                    'id' => 'work',
                    'type' => 'numbered',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Working at ORIGINA',
                    'title' => 'Capability and character.',
                    'intro' => 'The environment should reward clear thinking, rigorous execution, intellectual generosity, and the confidence to challenge assumptions responsibly.',
                    'items' => [
                        ['title' => 'Think', 'text' => 'Question deeply before acting.'],
                        ['title' => 'Build', 'text' => 'Translate knowledge into useful outcomes.'],
                        ['title' => 'Own', 'text' => 'Take responsibility for the result.'],
                        ['title' => 'Improve', 'text' => 'Raise the standard every cycle.'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Talent & collaboration',
                'title' => 'Do your best work with purpose.',
                'links' => [
                    ['href' => '/contact?subject=talent', 'label' => 'Talent enquiries'],
                    ['href' => '/about', 'label' => 'About ORIGINA', 'secondary' => true],
                ],
            ],
        ],

        'science' => [
            'path' => '/science',
            'title' => 'Science — ORIGINA™',
            'description' => 'ORIGINA’s scientific position, development framework, and institutional approach to biology-first innovation.',
            'hero' => [
                'crumb' => 'Science',
                'kicker' => 'ORIGINA / Science',
                'title' => 'Science with',
                'accent' => 'institutional discipline.',
                'intro' => 'ORIGINA operates at the intersection of biology, dermatology, formulation science, biotechnology, and human wellbeing. Skin science is where we begin — not where we end.',
                'image' => '/img/founder/founder-05.jpeg',
                'alt' => 'Dr. Elizabeth Consoli discussing formulation science',
                'caption' => 'Formulation science · Human context',
            ],
            'nav' => [
                ['id' => 'position', 'label' => 'Scientific position'],
                ['id' => 'systems', 'label' => 'Systems thinking'],
                ['id' => 'framework', 'label' => 'Framework'],
            ],
            'sections' => [
                [
                    'id' => 'position',
                    'type' => 'split',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Scientific position',
                    'title' => 'Skin of colour is where we begin.',
                    'lead' => 'What changes when human biology is studied from the perspective of melanin-rich skin?',
                    'paragraphs' => [
                        'Those populations have historically been underrepresented within dermatological research, clinical evidence, and product development. ORIGINA’s work begins there — as a starting point, not an institutional limit.',
                        'Skin colour is an important biological and clinical consideration — not a single biological category.',
                    ],
                    'items' => ['Fitzpatrick skin type', 'Ancestry', 'Phenotype', 'Disease state', 'Environmental exposure', 'Individual biology'],
                    'image' => '/img/founder/founder-08.jpeg',
                    'image_alt' => 'A multidisciplinary professional community around ORIGINA',
                    'caption' => 'Population-aware science',
                    'reverse' => true,
                ],
                [
                    'id' => 'systems',
                    'type' => 'numbered',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Systems thinking',
                    'title' => 'Every variable affects the whole.',
                    'items' => [
                        ['title' => 'Pigmentation', 'text' => 'Visible pigment biology interacts with inflammation, exposure, barrier condition, and individual context.'],
                        ['title' => 'Inflammation', 'text' => 'Inflammatory signalling can modify tolerance, recovery, and visible outcomes.'],
                        ['title' => 'Barrier function', 'text' => 'Intervention must account for skin integrity and resilience.'],
                        ['title' => 'Environment', 'text' => 'Climate, exposure and behaviour are part of the biological context.'],
                        ['title' => 'Cellular ageing', 'text' => 'Ageing-related processes affect tissue function over time.'],
                        ['title' => 'Metabolic stress', 'text' => 'Cellular stress influences the conditions within which products or technologies operate.'],
                    ],
                ],
                [
                    'id' => 'framework',
                    'type' => 'numbered',
                    'tone' => 'paper',
                    'eyebrow' => '03 · Development framework',
                    'title' => 'From hypothesis to product.',
                    'intro' => 'Thirteen disciplined stages — a controlled development pipeline, not thirteen generic product claims.',
                    'items' => array_map(
                        fn (string $title) => ['title' => $title, 'text' => null],
                        [
                            'Biological hypothesis',
                            'Literature & evidence review',
                            'Target / pathway selection',
                            'Ingredient & technology selection',
                            'Formulation development',
                            'Stability & compatibility assessment',
                            'Microbiological / safety evaluation',
                            'Analytical & quality testing',
                            'Regulatory classification',
                            'Human evaluation where appropriate',
                            'Manufacturing scale-up',
                            'Regulatory submission / registration',
                            'Post-market monitoring',
                        ]
                    ),
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Enter the scientific engine.',
                'links' => [
                    ['href' => '/labs', 'label' => 'ORIGINA Labs™'],
                    ['href' => '/science/evidence', 'label' => 'Evidence hierarchy', 'secondary' => true],
                ],
            ],
        ],

        'platforms' => [
            'path' => '/platforms',
            'title' => 'Scientific Platforms — ORIGINA',
            'description' => 'Proprietary scientific platforms developed within ORIGINA Labs, including BMX-24™ and BRP-1™.',
            'hero' => [
                'crumb' => 'Platforms',
                'kicker' => 'ORIGINA / Platforms',
                'title' => 'Proprietary science',
                'accent' => 'platforms.',
                'intro' => 'Scientific platforms support multiple products, protocols, and future applications. ™ indicates trademark status — not patent status unless explicitly documented.',
            ],
            'sections' => [
                [
                    'id' => 'architecture',
                    'type' => 'directory',
                    'tone' => 'paper',
                    'eyebrow' => 'Platform architecture',
                    'title' => 'Platforms emerge from ORIGINA Labs.',
                    'items' => [
                        [
                            'meta' => 'Platform 01 · Development',
                            'title' => 'BMX-24™',
                            'subtitle' => 'Proprietary Pigment Regulation Platform',
                            'text' => 'Developed as a proprietary pigment-regulation platform originating from research into non-hydroquinone approaches to hyperpigmentation in skin of colour. Clinical studies are not yet complete.',
                            'href' => '/divisions/b-melanox',
                            'link' => 'View platform context',
                        ],
                        [
                            'meta' => 'Platform 02 · Research',
                            'title' => 'BRP-1™',
                            'subtitle' => 'Proprietary Research Platform',
                            'text' => 'An institutional research platform under development within ORIGINA Labs. Described as proprietary — not as patented unless documentation supports such status.',
                            'href' => '/intellectual-property',
                            'link' => 'View IP context',
                        ],
                    ],
                ],
                [
                    'id' => 'distinction',
                    'type' => 'prose',
                    'tone' => 'sunk',
                    'eyebrow' => 'IP distinction',
                    'title' => 'Proprietary is not patented.',
                    'paragraphs' => [
                        'ORIGINA distinguishes proprietary platforms, trademarked names, patent applications, and granted patents. Platform descriptions use conservative language unless documentation supports a stronger status.',
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'See how ideas become institutional assets.',
                'links' => [
                    ['href' => '/intellectual-property', 'label' => 'Intellectual property'],
                    ['href' => '/labs', 'label' => 'ORIGINA Labs™', 'secondary' => true],
                ],
            ],
        ],

        'evidence' => [
            'path' => '/science/evidence',
            'title' => 'Clinical & Scientific Evidence — ORIGINA™',
            'description' => 'ORIGINA distinguishes hypothesis, formulation testing, human evaluation, and clinical evidence. Evidence has levels.',
            'hero' => [
                'crumb' => 'Evidence',
                'kicker' => 'ORIGINA / Evidence & Quality',
                'title' => 'Evidence has',
                'accent' => 'levels.',
                'intro' => 'ORIGINA is ambitious scientifically and conservative in claims. The strength of a claim must correspond to the strength of the evidence.',
            ],
            'nav' => [
                ['id' => 'ladder', 'label' => 'Evidence ladder'],
                ['id' => 'clinical', 'label' => 'Clinical research'],
                ['id' => 'records', 'label' => 'Research records'],
            ],
            'sections' => [
                [
                    'id' => 'ladder',
                    'type' => 'numbered',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Evidence ladder',
                    'title' => 'The evidence hierarchy.',
                    'intro' => 'Marketing language must not jump between evidence levels.',
                    'items' => array_map(
                        fn (string $title) => ['title' => $title],
                        [
                            'Scientific hypothesis',
                            'In-vitro evidence',
                            'Ex-vivo evidence',
                            'Formulation testing',
                            'Instrumental / biophysical testing',
                            'Pilot human evaluation',
                            'Controlled clinical study',
                            'Randomized controlled clinical trial',
                            'Systematic evidence',
                        ]
                    ),
                ],
                [
                    'id' => 'clinical',
                    'type' => 'detail',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Clinical research',
                    'title' => 'Product marketing and clinical research are separate.',
                    'intro' => 'Where clinical research is discussed, it is structured around disciplined methodology — not marketing language.',
                    'items' => [
                        ['title' => 'Scientifically justified protocols'],
                        ['title' => 'Ethics review'],
                        ['title' => 'Informed consent'],
                        ['title' => 'Participant safety'],
                        ['title' => 'Predefined endpoints'],
                        ['title' => 'Statistical methodology'],
                        ['title' => 'Adverse-event monitoring'],
                        ['title' => 'Data integrity'],
                        ['title' => 'Investigator responsibilities'],
                        ['title' => 'Appropriate reporting'],
                    ],
                ],
                [
                    'id' => 'records',
                    'type' => 'prose',
                    'tone' => 'paper',
                    'eyebrow' => '03 · Research records',
                    'title' => 'Research records are published when disclosure standards are met.',
                    'paragraphs' => [
                        'Future research records will support metadata including research title, platform, evidence level, population, methodology, and publication status.',
                        'Empty states are preferable to fabricated data.',
                    ],
                    'quote' => 'A study conducted by ORIGINA does not automatically mean clinically proven.',
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Understand institutional claim discipline.',
                'links' => [
                    ['href' => '/science/responsible-science', 'label' => 'Responsible science'],
                    ['href' => '/science/quality', 'label' => 'Quality framework', 'secondary' => true],
                ],
            ],
        ],

        'regulatory' => [
            'path' => '/science/regulatory',
            'title' => 'Regulatory Science — ORIGINA™',
            'description' => 'Science does not replace regulation. ORIGINA works across cosmetics, medicines, devices, and clinical research with appropriate classification.',
            'hero' => [
                'crumb' => 'Regulatory Science',
                'kicker' => 'ORIGINA / Evidence & Quality',
                'title' => 'Science does not',
                'accent' => 'replace regulation.',
                'intro' => 'Cosmetics, medicines, medical devices, and clinical investigations may follow different regulatory pathways. Classification precedes claims.',
            ],
            'sections' => [
                [
                    'id' => 'architecture',
                    'type' => 'detail',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Regulatory architecture',
                    'title' => 'Classification precedes claims.',
                    'items' => [
                        ['title' => 'Cosmetics', 'text' => 'Product categories subject to applicable cosmetic regulatory frameworks, including Tanzania Bureau of Standards (TBS) requirements for cosmetic products placed on the Tanzanian market.'],
                        ['title' => 'Medicines', 'text' => 'Subject to applicable Tanzania Medicines and Medical Devices Authority (TMDA) frameworks where products meet pharmaceutical regulatory requirements.'],
                        ['title' => 'Medical devices & diagnostics', 'text' => 'Subject to applicable TMDA frameworks where products meet medical device or diagnostic regulatory requirements—distinct from cosmetic classification.'],
                        ['title' => 'Clinical investigations', 'text' => 'Regulated clinical research remains conceptually separate from cosmetic product marketing. Clinical trials follow applicable TMDA pathways where required.'],
                    ],
                    'quote' => 'Regulatory classification precedes claims architecture.',
                ],
                [
                    'id' => 'clinical',
                    'type' => 'prose',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Clinical research',
                    'title' => 'Clinical research pathway.',
                    'paragraphs' => [
                        'Where regulated clinical research is conducted, the pathway includes applicable regulatory authorization, ethics review, informed consent, participant safety, predefined endpoints, statistical methodology, adverse-event monitoring, data integrity, investigator responsibilities, and appropriate reporting—distinct from cosmetic marketing.',
                        'Compliance work and framework alignment do not constitute regulatory approval unless explicitly documented. ORIGINA does not claim TBS Approved, TMDA Approved, or regulator approved status without underlying documentation.',
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the quality and claims framework.',
                'links' => [
                    ['href' => '/science/quality', 'label' => 'Quality framework'],
                    ['href' => '/science/responsible-science', 'label' => 'Claims discipline', 'secondary' => true],
                ],
            ],
        ],

        'quality' => [
            'path' => '/science/quality',
            'title' => 'Quality & Safety — ORIGINA™',
            'description' => 'Designed for quality. Tested for purpose. ORIGINA’s intended frameworks for regulatory compliance, GMP-aligned manufacturing, and product development.',
            'hero' => [
                'crumb' => 'Quality & Safety',
                'kicker' => 'ORIGINA / Evidence & Quality',
                'title' => 'Designed for quality.',
                'accent' => 'Tested for purpose.',
                'intro' => 'Quality is designed into the system. Framework intentions — not claims of existing certification unless documented.',
            ],
            'sections' => [
                [
                    'id' => 'pillars',
                    'type' => 'cards',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Quality pillars',
                    'title' => 'Quality by design.',
                    'items' => [
                        ['title' => 'Regulatory compliance', 'text' => 'Alignment with Tanzania and applicable export-market requirements for each product category.'],
                        ['title' => 'GMP-aligned manufacturing', 'text' => 'Appropriate controls around manufacturing, hygiene, documentation, and quality.'],
                        ['title' => 'Ingredient compliance', 'text' => 'Screening against applicable prohibited and restricted ingredient requirements.'],
                        ['title' => 'Microbiological quality', 'text' => 'Risk-based microbiological testing appropriate to the formulation.'],
                        ['title' => 'Stability', 'text' => 'Physical, chemical, and microbiological stability assessment as appropriate.'],
                        ['title' => 'Packaging compatibility', 'text' => 'Container-closure compatibility and product protection.'],
                        ['title' => 'Traceability', 'text' => 'Batch-level manufacturing documentation.'],
                        ['title' => 'Claims substantiation', 'text' => 'Claims should correspond to evidence.'],
                        ['title' => 'Post-market surveillance', 'text' => 'Complaint handling, adverse-event monitoring, and corrective action where required.'],
                    ],
                ],
                [
                    'id' => 'technical-file',
                    'type' => 'numbered',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Technical file',
                    'title' => 'Technical file architecture.',
                    'intro' => 'The difference between making formulas and building a regulated product-development organization.',
                    'items' => array_map(
                        fn (string $title) => ['title' => $title],
                        [
                            'Formula specification',
                            'Raw-material specifications',
                            'Supplier qualification',
                            'Certificate of Analysis documentation',
                            'Manufacturing specification',
                            'Batch records',
                            'Stability data',
                            'Microbiological testing',
                            'Packaging compatibility',
                            'Safety assessment',
                            'Claims substantiation',
                            'Labelling review',
                            'Regulatory documentation',
                            'Complaint / adverse-event records',
                            'Change-control history',
                        ]
                    ),
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'See regulatory alignment.',
                'links' => [
                    ['href' => '/science/regulatory', 'label' => 'Regulatory science'],
                ],
            ],
        ],

        'responsible-science' => [
            'path' => '/science/responsible-science',
            'title' => 'Responsible Science — ORIGINA™',
            'description' => 'Ambition without scientific inflation. ORIGINA’s institutional doctrine on evidence, claims, and scientific integrity.',
            'hero' => [
                'crumb' => 'Responsible Science',
                'kicker' => 'Institutional doctrine',
                'title' => 'Ambition without',
                'accent' => 'scientific inflation.',
                'intro' => 'ORIGINA is ambitious scientifically and conservative in claims. The strength of a claim must match the strength of the evidence.',
                'image' => '/img/founder/founder-05.jpeg',
                'alt' => 'Dr. Elizabeth Consoli explaining formulation science',
                'caption' => 'Evidence before exaggeration',
            ],
            'sections' => [
                [
                    'id' => 'doctrine',
                    'type' => 'statement',
                    'tone' => 'paper',
                    'eyebrow' => 'Doctrine',
                    'title' => 'If the evidence is preliminary, we call it preliminary.',
                    'quote' => 'If the evidence is strong, we show it. If we do not know, we say we do not know.',
                    'meta' => 'Scientific integrity before marketing certainty',
                ],
                [
                    'id' => 'rejections',
                    'type' => 'statement-list',
                    'tone' => 'noir',
                    'eyebrow' => '01 · Rejections',
                    'title' => 'What we reject.',
                    'items' => [
                        'Unsupported clinically proven claims',
                        'Exaggerated anti-ageing claims',
                        'Disease-treatment claims for products not authorized as medicines',
                        'Misleading before/after claims',
                        'Unsupported superiority claims',
                        'Invented clinical outcomes',
                        'Patented language without a patent basis',
                        'Regulatory language implying approval that has not occurred',
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the evidence architecture.',
                'links' => [
                    ['href' => '/science/evidence', 'label' => 'Evidence hierarchy'],
                    ['href' => '/science/regulatory', 'label' => 'Regulatory science', 'secondary' => true],
                ],
            ],
        ],

        'intellectual-property' => [
            'path' => '/intellectual-property',
            'title' => 'Intellectual Property — ORIGINA™',
            'description' => 'Ideas become institutional assets. ORIGINA identifies and protects formulations, platforms, technologies, and research outputs.',
            'hero' => [
                'crumb' => 'Intellectual Property',
                'kicker' => 'ORIGINA / Institution',
                'title' => 'Ideas become',
                'accent' => 'institutional assets.',
                'intro' => 'ORIGINA’s innovation architecture may identify and protect formulations, compositions, delivery systems, technologies, manufacturing processes, analytical methods, scientific platforms, trademarks, designs, and research outputs.',
            ],
            'sections' => [
                [
                    'id' => 'types',
                    'type' => 'detail',
                    'tone' => 'paper',
                    'eyebrow' => '01 · IP types',
                    'title' => 'What the institution protects.',
                    'items' => [
                        ['title' => 'Trademarks', 'text' => 'Brand names and identifiers including ORIGINA™, ORIGINA Labs™, B-Melanox™, BMX-24™, and division marks. ™ does not mean patented.'],
                        ['title' => 'Proprietary technology', 'text' => 'Platform innovations developed through institutional research.'],
                        ['title' => 'Proprietary know-how', 'text' => 'Formulation logic, processes, and institutional methods.'],
                        ['title' => 'Patent applications & grants', 'text' => 'Described only where explicit documentation supports such status.'],
                    ],
                ],
                [
                    'id' => 'platform-ip',
                    'type' => 'directory',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Platform IP',
                    'title' => 'Proprietary is not patented.',
                    'intro' => '™ indicates trademark status. Proprietary describes institutional ownership of know-how or platforms. Patent status is described only where explicit documentation supports it.',
                    'items' => [
                        ['meta' => 'Development', 'title' => 'BMX-24™', 'subtitle' => 'Proprietary Pigment Regulation Platform', 'text' => 'Clinical studies are not yet complete.', 'href' => '/divisions/b-melanox', 'link' => 'View platform'],
                        ['meta' => 'Research', 'title' => 'BRP-1™', 'subtitle' => 'Proprietary Research Platform', 'text' => 'Research platform under development within ORIGINA Labs.', 'href' => '/platforms', 'link' => 'View platform architecture'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the platform work.',
                'links' => [
                    ['href' => '/platforms', 'label' => 'Scientific platforms'],
                    ['href' => '/labs', 'label' => 'ORIGINA Labs™', 'secondary' => true],
                ],
            ],
        ],

        'divisions' => [
            'path' => '/divisions',
            'title' => 'Divisions — ORIGINA™',
            'description' => 'ORIGINA’s active and emerging divisions: B-Melanox™, BettyWorld, BValence™, DIVINE™, NOVIA™, Skin Safari™, and ORIGINA Labs™.',
            'hero' => [
                'crumb' => 'Divisions',
                'kicker' => 'Institutional divisions',
                'title' => 'Distinct expressions.',
                'accent' => 'Shared institution.',
                'intro' => 'Brands are expressions of the institution. Research is part of the institutional infrastructure.',
                'image' => '/img/products/bmelanox-09.jpeg',
                'alt' => 'ORIGINA product and lifestyle detail',
                'caption' => 'Institutional portfolio',
            ],
            'sections' => [
                [
                    'id' => 'architecture',
                    'type' => 'prose',
                    'tone' => 'paper',
                    'eyebrow' => 'Architecture',
                    'title' => 'How divisions connect.',
                    'lead' => 'Each division carries a specific scientific or human focus while operating under shared institutional standards.',
                    'paragraphs' => [
                        'ORIGINA Labs provides scientific infrastructure. Divisions translate institutional capability into focused expressions. Evidence, quality, responsible claims, design discipline, and institutional governance remain shared.',
                    ],
                    'quote' => 'Products are outputs. Brands are expressions. The institution is the system that holds them together.',
                ],
                [
                    'id' => 'directory',
                    'type' => 'directory',
                    'tone' => 'sunk',
                    'eyebrow' => 'Directory',
                    'title' => 'All divisions.',
                    'items_from' => 'divisions',
                ],
            ],
        ],

        'future' => [
            'path' => '/future',
            'title' => 'Future Divisions — ORIGINA',
            'description' => 'Explore the planned and future divisions within ORIGINA’s institutional framework.',
            'hero' => [
                'crumb' => 'Future',
                'kicker' => 'ORIGINA / Future',
                'title' => 'Built for the ideas',
                'accent' => 'still without names.',
                'intro' => 'ORIGINA’s framework is designed to expand when the capacity to execute with excellence arrives—not before.',
                'image' => '/img/founder/founder-09.jpeg',
                'alt' => 'Professional exchange representing future institutional collaboration',
                'caption' => 'Open possibility · disciplined expansion',
            ],
            'sections' => [
                [
                    'id' => 'discipline',
                    'type' => 'prose',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Discipline',
                    'title' => 'Expansion with discipline.',
                    'lead' => 'The institution is open-ended by design. Its standards are not.',
                    'paragraphs' => [
                        'New divisions are not created because an opportunity is fashionable. They emerge when ORIGINA has the knowledge, people, systems, and patience to execute them with integrity.',
                    ],
                ],
                [
                    'id' => 'horizon',
                    'type' => 'directory',
                    'tone' => 'noir',
                    'eyebrow' => 'Institutional horizon',
                    'title' => 'Planned → future → open possibility.',
                    'items_from' => 'future',
                ],
                [
                    'id' => 'test',
                    'type' => 'numbered',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Expansion test',
                    'title' => 'Before a new division begins.',
                    'items' => [
                        ['title' => 'Does it improve human life in a meaningful way?'],
                        ['title' => 'Can ORIGINA contribute something genuinely distinctive?'],
                        ['title' => 'Is the evidence, talent, and operating capacity present?'],
                        ['title' => 'Can excellence be sustained for the long term?'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Build the future',
                'title' => 'Bring the idea worth developing.',
                'links' => [
                    ['href' => '/contact', 'label' => 'Start a conversation'],
                    ['href' => '/labs', 'label' => 'Explore the Labs', 'secondary' => true],
                ],
            ],
        ],

        'contact' => [
            'path' => '/contact',
            'title' => 'Contact ORIGINA™ — Build with ORIGINA',
            'description' => 'Enquire with ORIGINA: scientific collaboration, manufacturing, investment, brand partnerships, and media.',
            'hero' => [
                'crumb' => 'Contact',
                'kicker' => 'Build with ORIGINA',
                'title' => 'Build with',
                'accent' => 'ORIGINA.',
                'intro' => 'Scientific collaboration, manufacturing development, investment, brand partnerships, and scientific communication.',
                'image' => '/img/founder/founder-09.jpeg',
                'alt' => 'Dr. Elizabeth Consoli in professional conversation',
                'caption' => 'Serious ideas deserve serious conversation',
            ],
            'sections' => [
                [
                    'id' => 'directory',
                    'type' => 'directory',
                    'tone' => 'noir',
                    'eyebrow' => 'Enquiry pathways',
                    'title' => 'Start with the right conversation.',
                    'intro' => 'The online submission workflow will be connected during the backend phase. For now, institutional enquiries are directed by email.',
                    'items' => [
                        ['meta' => '01', 'title' => 'Scientific Collaboration', 'text' => 'Research partnerships, academic collaboration, clinical research.', 'href' => 'mailto:info@origina.co?subject=Scientific%20Collaboration', 'link' => 'Compose email'],
                        ['meta' => '02', 'title' => 'Manufacturing & Development', 'text' => 'Formulation development, scale-up, manufacturing partnerships.', 'href' => 'mailto:info@origina.co?subject=Manufacturing%20%26%20Development', 'link' => 'Compose email'],
                        ['meta' => '03', 'title' => 'Investment', 'text' => 'ORIGINA Ventures, strategic capital, institutional partnerships.', 'href' => 'mailto:info@origina.co?subject=Investment', 'link' => 'Compose email'],
                        ['meta' => '04', 'title' => 'Brand & Commercial', 'text' => 'Distribution, retail, licensing, partnerships.', 'href' => 'mailto:info@origina.co?subject=Brand%20%26%20Commercial', 'link' => 'Compose email'],
                        ['meta' => '05', 'title' => 'Media & Education', 'text' => 'Skin Safari, scientific communication, interviews, documentary.', 'href' => 'mailto:info@origina.co?subject=Media%20%26%20Education', 'link' => 'Compose email'],
                    ],
                ],
                [
                    'id' => 'message',
                    'type' => 'numbered',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Message guide',
                    'title' => 'A useful first message.',
                    'intro' => 'Help us understand the substance of the conversation from the beginning.',
                    'items' => [
                        ['title' => 'Introduce yourself and your organisation.'],
                        ['title' => 'State the division or subject your enquiry concerns.'],
                        ['title' => 'Explain the opportunity, problem, or proposed relationship.'],
                        ['title' => 'Include the timing and the next step you are requesting.'],
                    ],
                ],
                [
                    'id' => 'direct',
                    'type' => 'contact',
                    'tone' => 'sunk',
                    'eyebrow' => 'Write to us',
                    'title' => 'A direct line to ORIGINA.',
                    'email' => 'info@origina.co',
                    'items' => [
                        ['label' => 'Location', 'value' => 'Dar es Salaam, Tanzania'],
                        ['label' => 'Response', 'value' => 'Business enquiries by email'],
                        ['label' => 'Working language', 'value' => 'English'],
                    ],
                    'notice' => 'Do not submit clinical trial participant data, detailed medical records, or other sensitive health information through general institutional contact.',
                ],
            ],
        ],

        'updates' => [
            'path' => '/updates',
            'title' => 'ORIGINA Updates',
            'description' => 'News, research publications, and institutional updates from ORIGINA.',
            'hero' => [
                'crumb' => 'Updates',
                'kicker' => 'Knowledge & progress',
                'title' => 'ORIGINA',
                'accent' => 'updates.',
                'intro' => 'News, research records, and institutional field notes.',
            ],
            'sections' => [
                [
                    'id' => 'archive',
                    'type' => 'empty',
                    'tone' => 'sunk',
                    'eyebrow' => 'Archive',
                    'title' => 'Publications',
                    'lead' => 'The publication archive is being prepared.',
                    'text' => 'The frontend is ready for publications, research records, institutional notes, and controlled disclosure metadata. Database-backed publishing is intentionally deferred to the backend phase.',
                ],
            ],
        ],

        'privacy' => [
            'path' => '/privacy',
            'title' => 'Privacy Policy — ORIGINA™',
            'description' => 'ORIGINA privacy policy, data protection information, and research-participant separation for website visitors.',
            'hero' => [
                'crumb' => 'Privacy',
                'kicker' => 'ORIGINA / Legal',
                'title' => 'Privacy & data',
                'accent' => 'architecture.',
                'intro' => 'How ORIGINA handles personal data collected through this website — separate from future clinical research participant workflows.',
            ],
            'sections' => [
                [
                    'id' => 'legal',
                    'type' => 'legal',
                    'tone' => 'paper',
                    'items' => [
                        ['title' => 'Scope', 'paragraphs' => ['This policy applies to personal data collected through the ORIGINA public website and institutional enquiries.', 'It does not replace dedicated research-participant privacy information where regulated clinical research is conducted.']],
                        ['title' => 'Data we collect', 'paragraphs' => ['When digital enquiry forms are introduced, submissions may include name, email, optional organization and phone, enquiry category, and message content.', 'Privacy-conscious analytics may collect anonymized page metrics without third-party advertising cookies where such analytics are introduced.']],
                        ['title' => 'Purpose', 'paragraphs' => ['Data will be used to respond to institutional enquiries, manage research and partnership conversations, and improve the website.', 'General contact channels must not be used to submit clinical participant data, detailed medical histories, or other sensitive health records.']],
                        ['title' => 'Cookies', 'paragraphs' => ['ORIGINA aims to minimize non-essential cookies.', 'If cookie-based tools are introduced in future, this policy will be updated before deployment.']],
                        ['title' => 'Research participants', 'paragraphs' => ['Regulated clinical research workflows remain separate from general website contact.', 'Where research participant information is collected, dedicated privacy notices, consent mechanisms, and ethics-reviewed processes will apply.']],
                        ['title' => 'Your rights', 'paragraphs' => ['You may request access, correction, or deletion of personal enquiry data held by ORIGINA where applicable.', 'Contact info@origina.co for privacy enquiries.']],
                        ['title' => 'Security', 'paragraphs' => ['Access to personal information should be limited to authorized institutional users and protected by proportionate technical and organizational measures.', 'No system can guarantee absolute security.']],
                        ['title' => 'Updates', 'paragraphs' => ['This policy may be updated as ORIGINA’s digital architecture, regulatory context, or research programmes evolve.', 'Material changes will be reflected on this page.']],
                    ],
                ],
            ],
        ],

        'terms' => [
            'path' => '/terms',
            'title' => 'Terms of Use — ORIGINA™',
            'description' => 'Terms governing use of the ORIGINA institutional website.',
            'hero' => [
                'crumb' => 'Terms',
                'kicker' => 'ORIGINA / Legal',
                'title' => 'Terms of',
                'accent' => 'Use.',
                'intro' => 'Conditions governing use of this institutional website.',
            ],
            'sections' => [
                [
                    'id' => 'legal',
                    'type' => 'legal',
                    'tone' => 'paper',
                    'items' => [
                        ['title' => 'Institutional information', 'paragraphs' => ['This website provides institutional information about ORIGINA™. Content does not constitute medical advice, product authorization, regulatory approval, or a substitute for professional care.']],
                        ['title' => 'Scientific and product claims', 'paragraphs' => ['Product information, availability, scientific status, and claims remain subject to formal validation and regulatory requirements.', 'Research-stage concepts and future programmes are identified as such where applicable.']],
                        ['title' => 'Intellectual property', 'paragraphs' => ['ORIGINA names, marks, content, designs, research descriptions, and institutional materials may be protected by intellectual-property rights. Do not reproduce institutional content without permission.']],
                        ['title' => 'External services', 'paragraphs' => ['Where external services or links are introduced, their own terms and privacy practices may apply. ORIGINA should minimize unnecessary third-party dependencies.']],
                        ['title' => 'Contact', 'paragraphs' => ['For institutional or legal enquiries, contact info@origina.co.']],
                    ],
                ],
            ],
        ],
    ],

    'divisions' => [
        'bettyworld' => [
            'path' => '/divisions/bettyworld',
            'title' => 'BettyWorld — Everyday Skincare for Skin of Colour',
            'description' => 'BettyWorld is ORIGINA’s everyday dermatological skincare division. Daily care, barrier preservation, practical dermatology.',
            'body_class' => 'division-page division-page--betty',
            'hero' => [
                'crumb' => 'Divisions / BettyWorld',
                'kicker' => 'Division / Everyday dermatological skincare',
                'title' => 'Daily care.',
                'accent' => 'Consistent use.',
                'intro' => 'Everyday skincare for skin of colour. Core philosophy: daily care, consistent use, barrier preservation, practical dermatology.',
                'dark' => true,
            ],
            'sections' => [
                [
                    'type' => 'cards',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Division logic',
                    'title' => 'Two complementary expressions.',
                    'intro' => 'BettyWorld handles everyday dermatological skincare. B-Melanox handles advanced pigmentation science.',
                    'items' => [
                        ['meta' => 'BettyWorld · Development', 'title' => 'Everyday dermatological care', 'text' => 'Everyday skin-of-colour skincare · Barrier preservation · Practical dermatology · Daily routines'],
                        ['meta' => 'B-Melanox™ · Active', 'title' => 'Advanced pigmentation science', 'text' => 'Deeper pigmentation science · Platform innovation · Intensive pigment management · Research-led protocols', 'href' => '/divisions/b-melanox'],
                    ],
                ],
                [
                    'type' => 'tags',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Ecosystem',
                    'title' => 'Everyday dermatological portfolio.',
                    'items' => ['Cleanser', 'Moisturizer', 'Sunscreen', 'Exfoliator', 'Daily pigmentation-care products', 'Everyday dermatological formulations'],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the pigmentation platform.',
                'links' => [
                    ['href' => '/divisions/b-melanox', 'label' => 'B-Melanox™'],
                    ['href' => '/contact', 'label' => 'Enquire', 'secondary' => true],
                ],
            ],
        ],

        'bvalence' => [
            'path' => '/divisions/bvalence',
            'title' => 'BValence™ — Ageing & Longevity Biology',
            'description' => 'BValence is ORIGINA’s ageing-science platform exploring biological processes associated with ageing.',
            'body_class' => 'division-page division-page--neutral',
            'hero' => [
                'crumb' => 'Divisions / BValence™',
                'kicker' => 'Division / Ageing & longevity biology',
                'title' => 'Ageing is',
                'accent' => 'biology.',
                'intro' => 'BValence is ORIGINA’s ageing-science research platform — using appropriately conservative language.',
                'dark' => true,
            ],
            'sections' => [
                [
                    'type' => 'prose',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Platform',
                    'title' => 'Conservative language. Serious science.',
                    'paragraphs' => [
                        'BValence explores how biological processes associated with ageing may be modulated, delayed, or better preserved — not reversed, prevented, or cured.',
                        'Initial research population can include skin of colour while scientific questions may extend more broadly.',
                    ],
                ],
                [
                    'type' => 'detail',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Research domains',
                    'title' => 'Ageing biology domains.',
                    'items' => [
                        ['title' => 'Extracellular Matrix', 'text' => 'Collagen, elastin and matrix organization.'],
                        ['title' => 'Cellular Senescence', 'text' => 'Senescent-cell biology and relevance to tissue ageing.'],
                        ['title' => 'Mitochondrial Biology', 'text' => 'Cellular energy and oxidative stress.'],
                        ['title' => 'Inflammaging', 'text' => 'Chronic inflammatory signalling associated with ageing.'],
                        ['title' => 'Glycation', 'text' => 'AGE-related effects on tissue structure and function.'],
                        ['title' => 'DNA & Cellular Protection', 'text' => 'Genomic stability and cellular stress responses.'],
                        ['title' => 'Longevity Biology', 'text' => 'Tissue maintenance and biological resilience.'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Follow the research engine.',
                'links' => [['href' => '/labs', 'label' => 'ORIGINA Labs™']],
            ],
        ],

        'divine' => [
            'path' => '/divisions/divine',
            'title' => 'DIVINE™ — Luxury Makeup Science',
            'description' => 'DIVINE is ORIGINA’s luxury makeup science division: colour science, cosmetic formulation, skin compatibility, and luxury aesthetics.',
            'body_class' => 'division-page division-page--divine',
            'hero' => [
                'crumb' => 'Divisions / DIVINE™',
                'kicker' => 'Division / Luxury makeup science',
                'title' => 'Luxury makeup.',
                'accent' => 'Biology-aware design.',
                'intro' => 'Colour science + cosmetic formulation + skin compatibility + luxury aesthetics.',
                'dark' => true,
            ],
            'sections' => [
                [
                    'type' => 'detail',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Scientific combination',
                    'title' => 'Makeup designed for skin of colour.',
                    'items' => [
                        ['title' => 'Colour science', 'text' => 'Pigment behaviour, undertone, and performance across skin of colour.'],
                        ['title' => 'Cosmetic formulation', 'text' => 'Stable, compatible formulations designed for repeated use.'],
                        ['title' => 'Skin compatibility', 'text' => 'Biology-aware design — not skin adaptation to industry norms.'],
                        ['title' => 'Luxury aesthetics', 'text' => 'Premium execution within the institutional design system.'],
                    ],
                    'quote' => 'Makeup should not require skin of colour to adapt to the industry.',
                ],
            ],
            'cta' => [
                'eyebrow' => 'Continue',
                'title' => 'Explore the division.',
                'links' => [['href' => '/contact', 'label' => 'DIVINE enquiries']],
            ],
        ],

        'novia' => [
            'path' => '/divisions/novia',
            'title' => 'NOVIA™ — Luxury Body Care',
            'description' => 'NOVIA is ORIGINA’s luxury body care division: sensory experience meets formulation engineering.',
            'body_class' => 'division-page division-page--novia',
            'hero' => [
                'crumb' => 'Divisions / NOVIA™',
                'kicker' => 'Luxury body care',
                'title' => 'Sensory experience meets',
                'accent' => 'formulation engineering.',
                'intro' => 'NOVIA focuses on texture, sensory performance, barrier compatibility, elegant formulation, and repeatable quality—not generic lifestyle positioning.',
                'image' => '/img/founder/founder-07.jpeg',
                'alt' => 'Woman enjoying an active self-care moment beside a tennis court',
                'caption' => 'Self-care in motion',
                'dark' => true,
            ],
            'sections' => [
                [
                    'type' => 'split',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Position',
                    'title' => 'Formulation science for the body.',
                    'lead' => 'An ORIGINA formulation-science expression applied to body care.',
                    'paragraphs' => [
                        'NOVIA is not a generic wellness brand. It is disciplined luxury body care built on institutional formulation standards—texture, sensory performance, barrier compatibility, and repeatable quality.',
                    ],
                    'image' => '/img/founder/founder-07.jpeg',
                    'image_alt' => 'Woman enjoying an active self-care moment beside a tennis court',
                    'caption' => 'Self-care in motion',
                    'reverse' => true,
                ],
                [
                    'type' => 'statement-list',
                    'tone' => 'noir',
                    'eyebrow' => 'Manifesto',
                    'title' => 'Care without apology.',
                    'items' => ['Beauty is not permission.', 'Care is not apology.', 'Ritual is not excess.'],
                ],
                [
                    'type' => 'cards',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Ecosystem',
                    'title' => 'The world of NOVIA.',
                    'items' => [
                        ['meta' => 'I', 'title' => 'Personal care', 'text' => 'Textures, scents, and formulations that transform daily body care into considered ritual.'],
                        ['meta' => 'II', 'title' => 'Beauty & elegance', 'text' => 'Products and experiences that celebrate feminine beauty across expressions and skin tones.'],
                        ['meta' => 'III', 'title' => 'Lifestyle & wellness', 'text' => 'Intentional living that reaches beyond products into presence, environment, and wellbeing.'],
                        ['meta' => 'IV', 'title' => 'Education', 'text' => 'Knowledge that helps women understand, care for, and celebrate their own skin and body.'],
                        ['meta' => 'V', 'title' => 'Community', 'text' => 'A gathering of women who are educated, empowered, and unapologetically alive.'],
                        ['meta' => 'VI', 'title' => 'Confidence', 'text' => 'Every touchpoint designed to leave the woman experiencing it more powerfully herself.'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'The lifestyle expression',
                'title' => 'Enter the world of NOVIA.',
                'links' => [
                    ['href' => '/contact', 'label' => 'NOVIA enquiries'],
                    ['href' => '/divisions/b-melanox', 'label' => 'Explore B-Melanox', 'secondary' => true],
                ],
            ],
        ],

        'skin-safari' => [
            'path' => '/divisions/skin-safari',
            'title' => 'Skin Safari™ — Education & Scientific Communication',
            'description' => 'Skin Safari is ORIGINA’s education, media, and scientific communication platform. Science should travel.',
            'body_class' => 'division-page division-page--neutral',
            'hero' => [
                'crumb' => 'Divisions / Skin Safari™',
                'kicker' => 'Division / Scientific communication',
                'title' => 'Science should',
                'accent' => 'travel.',
                'intro' => 'Education, media, and scientific communication — designed more like a scientific publication platform than a product brand.',
                'dark' => true,
            ],
            'sections' => [
                [
                    'type' => 'tags',
                    'tone' => 'paper',
                    'eyebrow' => '01 · Focus areas',
                    'title' => 'Where knowledge goes public.',
                    'items' => ['Dermatology', 'Skin of colour', 'Cosmetic science', 'Ingredient science', 'Myth correction', 'Research translation', 'Clinical education', 'African scientific innovation'],
                ],
                [
                    'type' => 'detail',
                    'tone' => 'sunk',
                    'eyebrow' => '02 · Future platform',
                    'title' => 'Future capabilities.',
                    'intro' => 'Skin Safari is in development as ORIGINA’s education and scientific communication platform — distinct from product marketing and division commerce.',
                    'items' => [
                        ['title' => 'Documentaries', 'text' => 'Long-form scientific storytelling.'],
                        ['title' => 'Courses', 'text' => 'Structured education for professionals and informed audiences.'],
                        ['title' => 'Publications', 'text' => 'Research translation and institutional writing.'],
                        ['title' => 'Interviews', 'text' => 'Conversations with scientists, clinicians, and innovators.'],
                        ['title' => 'Scientific media', 'text' => 'Institutional communication without diluting rigor.'],
                        ['title' => 'Professional education', 'text' => 'Training pathways for qualified audiences.'],
                    ],
                ],
            ],
            'cta' => [
                'eyebrow' => 'Media',
                'title' => 'Bring a communication opportunity.',
                'links' => [['href' => '/contact?subject=media', 'label' => 'Media enquiries']],
            ],
        ],
    ],

    'future' => [
        'academy' => [
            'path' => '/future/academy',
            'title' => 'ORIGINA Academy — Planned',
            'description' => 'A planned education and talent platform for future innovators, researchers, clinicians, entrepreneurs, and creators.',
            'hero' => ['crumb' => 'Future / Academy', 'kicker' => 'I · Planned', 'title' => 'ORIGINA', 'accent' => 'Academy.', 'intro' => 'Develop future innovators, researchers, clinicians, entrepreneurs, and creators. Education · Training · Talent.'],
            'sections' => [[
                'type' => 'tags', 'tone' => 'paper', 'eyebrow' => 'Focus areas', 'title' => 'Capability before scale.',
                'lead' => 'A future education platform intended to grow institutional capability around science, formulation, entrepreneurship, and innovation.',
                'items' => ['Researchers', 'Clinicians', 'Formulators', 'Scientists', 'Entrepreneurs', 'Innovators', 'Creators'],
            ]],
            'cta' => ['eyebrow' => 'Status', 'title' => 'Planned institutional direction.', 'links' => [['href' => '/future', 'label' => 'Return to the horizon']]],
        ],
        'ventures' => [
            'path' => '/future/ventures',
            'title' => 'ORIGINA Ventures — Planned',
            'description' => 'A planned incubation, investment, and innovation platform supporting internal and aligned external innovation.',
            'hero' => ['crumb' => 'Future / Ventures', 'kicker' => 'II · Planned', 'title' => 'ORIGINA', 'accent' => 'Ventures.', 'intro' => 'Incubation · Investment · Innovation. Supporting internal and aligned external innovation.'],
            'sections' => [[
                'type' => 'tags', 'tone' => 'paper', 'eyebrow' => 'Focus areas', 'title' => 'Innovation with institutional fit.',
                'lead' => 'This planned direction does not imply that an operating investment fund currently exists.',
                'items' => ['Incubation', 'Strategic partnerships', 'Aligned external innovators', 'Institutional IP pathways'],
            ]],
            'cta' => ['eyebrow' => 'Status', 'title' => 'Planned institutional direction.', 'links' => [['href' => '/future', 'label' => 'Return to the horizon']]],
        ],
        'research-institute' => [
            'path' => '/future/research-institute',
            'title' => 'ORIGINA Research Institute — Future',
            'description' => 'A future advanced research and clinical science institution across dermatology, skin biology, regenerative technologies, and biotechnology.',
            'hero' => ['crumb' => 'Future / Research Institute', 'kicker' => 'III · Future', 'title' => 'ORIGINA Research', 'accent' => 'Institute.', 'intro' => 'Advanced research · Clinical science · Long-horizon biological investigation.'],
            'sections' => [[
                'type' => 'tags', 'tone' => 'paper', 'eyebrow' => 'Future fields', 'title' => 'A research institution, if and when capacity is ready.',
                'lead' => 'Future institutional development — not presented as an operating entity unless established.',
                'items' => ['Dermatology', 'Skin biology', 'Regenerative technologies', 'Ageing biology', 'Biotechnology', 'Clinical science', 'Future therapeutic technologies'],
            ]],
            'cta' => ['eyebrow' => 'Status', 'title' => 'Future institutional direction.', 'links' => [['href' => '/future', 'label' => 'Return to the horizon']]],
        ],
        'foundation' => [
            'path' => '/future/foundation',
            'title' => 'ORIGINA Foundation — Future',
            'description' => 'A future impact, education, opportunity, and scientific-access direction.',
            'hero' => ['crumb' => 'Future / Foundation', 'kicker' => 'IV · Future', 'title' => 'ORIGINA', 'accent' => 'Foundation.', 'intro' => 'Impact · Education · Opportunity.'],
            'sections' => [[
                'type' => 'tags', 'tone' => 'paper', 'eyebrow' => 'Future focus', 'title' => 'Opportunity through knowledge.',
                'lead' => 'Planned institutional direction — distinct from current operating divisions.',
                'items' => ['Scholarships', 'Scientific education', 'Community development', 'Access to knowledge', 'Future African innovators'],
            ]],
            'cta' => ['eyebrow' => 'Status', 'title' => 'Future institutional direction.', 'links' => [['href' => '/future', 'label' => 'Return to the horizon']]],
        ],
        'product-divisions' => [
            'path' => '/future/product-divisions',
            'title' => 'Future Product & Technology Divisions — ORIGINA',
            'description' => 'Potential future divisions across nutritional science, medical devices, biotechnology, regenerative technologies, and personal health technologies.',
            'hero' => ['crumb' => 'Future / Product Divisions', 'kicker' => 'V · Future', 'title' => 'Future product &', 'accent' => 'technology divisions.', 'intro' => 'Expansion remains subject to scientific feasibility, regulatory classification, and institutional capacity.'],
            'sections' => [[
                'type' => 'tags', 'tone' => 'paper', 'eyebrow' => 'Potential fields', 'title' => 'Fields that may become divisions.',
                'items' => ['Nutritional science', 'Medical devices', 'Biotechnology', 'Regenerative technologies', 'Personal health technologies', 'Future therapeutic fields'],
            ]],
            'cta' => ['eyebrow' => 'Status', 'title' => 'Future institutional direction.', 'links' => [['href' => '/future', 'label' => 'Return to the horizon']]],
        ],
        'unnamed' => [
            'path' => '/future/unnamed',
            'title' => 'What Has Not Yet Been Named — ORIGINA',
            'description' => 'ORIGINA leaves room for discoveries that do not yet have a commercial category.',
            'hero' => ['crumb' => 'Future / Open Possibility', 'kicker' => '∞ · Open possibility', 'title' => 'What has not yet', 'accent' => 'been named.', 'intro' => 'ORIGINA was deliberately designed to accommodate discoveries that do not yet have a commercial category.'],
            'sections' => [[
                'type' => 'statement', 'tone' => 'noir', 'eyebrow' => 'Curiosity · Courage · The unknown', 'title' => 'The final destination is intentionally undefined.', 'quote' => 'The standard for reaching it is not.',
            ]],
            'cta' => ['eyebrow' => 'Explore', 'title' => 'Return to the institutional horizon.', 'links' => [['href' => '/future', 'label' => 'Future architecture']]],
        ],
    ],

    'directories' => [
        'divisions' => [
            ['meta' => 'Active', 'title' => 'ORIGINA Labs™', 'subtitle' => 'Research · Formulation · Innovation · IP', 'text' => 'The scientific engine.', 'href' => '/labs', 'link' => 'Enter Labs'],
            ['meta' => 'Active', 'title' => 'B-Melanox™', 'subtitle' => 'Pigmentation Science', 'text' => 'Scientific pigmentation division.', 'href' => '/divisions/b-melanox', 'link' => 'View division'],
            ['meta' => 'Development', 'title' => 'BettyWorld', 'subtitle' => 'Everyday Dermatological Skincare', 'text' => 'Daily care for skin of colour.', 'href' => '/divisions/bettyworld', 'link' => 'View division'],
            ['meta' => 'Research', 'title' => 'BValence™', 'subtitle' => 'Ageing & Longevity Biology', 'text' => 'Ageing is biology.', 'href' => '/divisions/bvalence', 'link' => 'View division'],
            ['meta' => 'Planned', 'title' => 'DIVINE™', 'subtitle' => 'Luxury Makeup Science', 'text' => 'Biology-aware colour science.', 'href' => '/divisions/divine', 'link' => 'View division'],
            ['meta' => 'Active', 'title' => 'NOVIA™', 'subtitle' => 'Luxury Body Care', 'text' => 'Formulation engineering for the body.', 'href' => '/divisions/novia', 'link' => 'View division'],
            ['meta' => 'Emerging', 'title' => 'Skin Safari™', 'subtitle' => 'Education · Media · Scientific Communication', 'text' => 'Science should travel.', 'href' => '/divisions/skin-safari', 'link' => 'View division'],
        ],
        'future' => [
            ['meta' => 'I · Planned', 'title' => 'ORIGINA Academy', 'subtitle' => 'Education · Training · Talent', 'text' => 'Develop future innovators, researchers, clinicians, entrepreneurs, and creators.', 'href' => '/future/academy', 'link' => 'View horizon'],
            ['meta' => 'II · Planned', 'title' => 'ORIGINA Ventures', 'subtitle' => 'Incubation · Investment · Innovation', 'text' => 'Supporting internal and aligned external innovation.', 'href' => '/future/ventures', 'link' => 'View horizon'],
            ['meta' => 'III · Future', 'title' => 'ORIGINA Research Institute', 'subtitle' => 'Advanced Research · Clinical Science', 'text' => 'Future institutional development — not presented as an operating entity unless established.', 'href' => '/future/research-institute', 'link' => 'View horizon'],
            ['meta' => 'IV · Future', 'title' => 'ORIGINA Foundation', 'subtitle' => 'Impact · Education · Opportunity', 'text' => 'Planned institutional direction.', 'href' => '/future/foundation', 'link' => 'View horizon'],
            ['meta' => 'V · Future', 'title' => 'Future Product & Technology Divisions', 'subtitle' => 'Long-horizon capability', 'text' => 'Potential future fields subject to feasibility, regulation, and capacity.', 'href' => '/future/product-divisions', 'link' => 'View horizon'],
            ['meta' => '∞ · Open possibility', 'title' => 'What has not yet been named', 'subtitle' => 'Curiosity · Courage · The unknown', 'text' => 'Room for discoveries that do not yet have a commercial category.', 'href' => '/future/unnamed', 'link' => 'Explore possibility'],
        ],
    ],
];
